---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: appropriate/curl
    tag: latest

inputs:
- name: findings

run:
  path: sh
  args:
  - -ec
  - |
    curl -X POST --data-urlencode \
      "payload={\"channel\": \"$SLACK_CHANNEL\", \"username\": \"Sonar Police\", \"text\": \"I found the following issues in *$SONARQUBE_COMPONENT*:\n\`\`\`Code Smells: $(cat findings/code_smells)\nVulnerabilities: $(cat findings/vulnerabilities)\nBugs: $(cat findings/bugs)\`\`\`\", \"icon_emoji\": \":female-police-officer:\"}" \
      $SLACK_WEBHOOK_URL
